### PR TITLE
Add additional feat-image controls for post headers

### LINKED ISSUE #9: [Feature] Add option for Featured Image "Above Header" on Blog Post
**Is your feature request related to a problem? Please describe.**
Currently, the "Blog Page" controls have an option to place the featured image above or below the post title and meta (referred to as the "Header" in the controls):
image

However, on "Blog Posts," there is only an option to include it below the header, not above.
image

Users are requesting that these two controls have parity for a more consistent overall appearance.

**Describe the solution you'd like**
Add an option to include the featured image in either the Header background, or Above or Below the Header.

**Additional context**
This feature was [requested in the BoldGrid Support Center.](https://www.boldgrid.com/support/boldgrid-crio-supertheme-product-guide/customizing-your-blog-page-with-boldgrid-crio/#comment-4755)

### PR DESCRIPTION
**Pull request by jamesros161**
Resolves #9

[crio-2.19.0-issue-9.zip](https://github.com/BoldGrid/crio/files/10521410/crio-2.19.0-issue-9.zip)

Testing Instructions
1. Install Crio and activate starter content ( or install an inspiration with a blog, then replace with this zip ).
2. Open the Customizer and navigate to `Design > Blog > Posts > Featured Images`
3. Ensure that you see four options for the `Position` control. They should be `Header Background, Above Header, Below Header, and In Content`
4. Select all four options, ensuring they appear correctly in the preview, publish, and check that they appear correctly on the front end.
5. When selecting `Above Header and Below Header` you will see another control appear called `Featured Image Display Type` which will allow you to select either `Background` or `Image` . Ensure both options display correctly in both positions, in the preview and when published.
6. When choosing the type `background` you will see a slider show up allowing you to specify the height of the background. Ensure the control changes are reflected in the preview and when published, for both above and below header.
7. When choosing the type `image` you can select the image size and alignment. Ensure these controls are working in the preview and when published.
8. When choosing the position `In Content` ensure that the image size and alignment controls are shown, and work as expected.

### CODE REVIEW

**Review by avonville — APPROVED** [review]

**Comment by nicolepaschen** [comment]
Above Header / Left and Right alignment I think has too much padding above and below the image. The center one looks much better / closer to the other elements.

**Comment by nicolepaschen** [comment]
Above Header / None alignment shows on the left side of the Customizer but when I close it it's centered (my last saved location)
none-alignment

**Comment by nicolepaschen** [comment]
Should Above Header / Background / Height have a desktop and mobile height option? 400px seems reasonable on desktop but on a mobile device that's half the screen

**Comment by jamesros161** [comment]
> 



> Should Above & Below Header / Background / Height have a desktop and mobile height option? 400px seems reasonable on desktop but on a mobile device that's half the screen

Maybe instead, I could let the user input units.
then you could do 1rem, 1em, 1vh ( representing height of viewport ). etc. This would let them just select an appropriate height that is auto responsive, and less confusing for the customer.

**Comment by nicolepaschen** [comment]
Featured Images > Hide control no longer works it still shows as the header background.

**Comment by nicolepaschen** [comment]
Please double check behavior with MFW designs (Burger Bar)

**Comment by nicolepaschen** [comment]
image

If I have Content Container for Page Titles set to full width and Featured Image Above Header / Image / Medium / Left the image appears right next to the page title

**Comment by nicolepaschen** [comment]
beta1 looks good!

**Comment by nicolepaschen** [comment]
% control doesn't work as expected, okay to just remove entirely.

**Pull request merged**
